AWSTemplateFormatVersion: 2010-09-09
Description: Space Mantra vpn  SERVER.
Parameters:
  VpcId:
    Description: Select your VPC Id.
    Type: 'AWS::EC2::VPC::Id'
    Default: ''
  SubnetId1:
    Description: Select your Subnet Id ap-southeast-2a.
    Type: 'AWS::EC2::Subnet::Id'
    Default: ''
  SshServerKeyName:
    Description: Name of an existing EC2 KeyPair to Prod Server.
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
  InstanceAMIId:
    Description: Type the base Ami Id.
    Type: String
    Default: ''
  InstanceType:
    Description: Type the instance.
    Type: String
    Default: t2.micro
  InstanceSecurityGroupName:
    Description: Enter the security Group Name.
    Type: String
    Default: ''
  Appname:
    Description: Enter the Application Name.
    Type: String
    Default: 'vpn'
  Clustername:
    Description: Enter the Cluster Name.
    Type: String
    Default: 'na'
  Environmentname:
    Description: Enter the Environmentname Name.
    Type: String
    Default: 'test'
  RoleTag:
    Description: Enter the role of the Resource.
    Type: String
    Default: 'OpenVpn Server'
  Remark:
    Description: Enter the Rake Name.
    Type: String
    Default: 'OpenVpn Server'  
  Ec2RootVolumeSize:
    Description: RootVolumeSize minimum value in GB.
    Type: Number
    MinValue: 10
  InstanceName1:
    Description: Enter the Name of the Instance.
    Default: 'OpenVpn-server'
    Type: String
  ProdRoles:
    Description: Enter the Role Name.
    Type: String
    Default: 'OpenVpn-server-role'
Resources:
  ProdWebInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref ProdRoles
  EC2ServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: EC2 Server Security Group
      GroupName: !Ref InstanceSecurityGroupName
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: '22'
          ToPort: '22'
          CidrIp: 10.180.0.0/16  
          Description: SSH allowed from VPC Network.         
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Ref InstanceSecurityGroupName
        - Key: appname
          Value: !Ref Appname
        - Key: businessunit
          Value: default
        - Key: environment
          Value: !Ref Environmentname
        - Key: remarks
          Value: !Ref Remark
  
  EC2Ec2Instance1:
    Type: 'AWS::EC2::Instance'
    DependsOn:
      - EC2ServerSecurityGroup
    Properties:
      DisableApiTermination: 'True'
      InstanceInitiatedShutdownBehavior: stop
      IamInstanceProfile: !Ref ProdWebInstanceProfile
      ImageId: !Ref InstanceAMIId
      InstanceType: !Ref InstanceType
      KeyName: !Ref SshServerKeyName
      Monitoring: 'false'
      Tags:
        - Key: Name
          Value: !Ref 'AWS::StackName'
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            DeleteOnTermination: 'true'
            VolumeSize: !Ref Ec2RootVolumeSize
            Encrypted: 'true'
            VolumeType: "gp2"
            
      Tags:
        - Key: Name
          Value: !Ref InstanceName1
        - Key: backup
          Value: 'yes:f=1d:r=7d'
        - Key: appname
          Value: !Ref Appname
        - Key: businessunit
          Value: default
        - Key: cluster
          Value: !Ref Clustername
        - Key: environment
          Value: !Ref Environmentname
        - Key: ownername
          Value: Space-Mantra
        - Key: role
          Value: !Ref RoleTag
        - Key: starttime
          Value: na
        - Key: stoptime
          Value: na
        - Key: created_by
          Value: uipl  
      NetworkInterfaces:
        - DeleteOnTermination: 'true'
          Description: Primary network interface
          DeviceIndex: 0
          SubnetId: !Ref SubnetId1
          GroupSet:
            - !Ref EC2ServerSecurityGroup